// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/core.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiCoreInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -725432860;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_openphon',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  int crateApiCoreSoundChannels({required Sound that});

  double crateApiCoreSoundDurationS({required Sound that});

  Future<WaveformEnvelope> crateApiCoreSoundEnvelope({
    required Sound that,
    required double t0S,
    required double t1S,
    required int nBuckets,
  });

  Future<void> crateApiCoreSoundExportRangeWav({
    required Sound that,
    required double t0S,
    required double t1S,
    required String path,
  });

  Future<F0TrackData> crateApiCoreSoundF0({
    required Sound that,
    required double timeStepS,
    required double f0MinHz,
    required double f0MaxHz,
  });

  Future<F0CandidatesData> crateApiCoreSoundF0Candidates({
    required Sound that,
    required double timeStepS,
    required double f0MinHz,
    required double f0MaxHz,
  });

  Future<FormantTrackData> crateApiCoreSoundFormants({
    required Sound that,
    required double timeStepS,
    required int maxFormants,
    required double ceilingHz,
  });

  Future<IntensityTrackData> crateApiCoreSoundIntensity({
    required Sound that,
    required double timeStepS,
    required double minPitchHz,
  });

  Future<Sound> crateApiCoreSoundLoad({required String path});

  int crateApiCoreSoundSampleRate({required Sound that});

  Future<SpectrogramData> crateApiCoreSoundSpectrogramRange({
    required Sound that,
    required double t0S,
    required double t1S,
    required double windowS,
    required double timeStepS,
    required double maxFreqHz,
    required double preEmphasisHz,
  });

  Future<VoiceReportData> crateApiCoreSoundVoiceReport({
    required Sound that,
    required double t0S,
    required double t1S,
    required double f0MinHz,
    required double f0MaxHz,
    F0TrackData? f0,
  });

  Future<SpectrogramData> crateApiCoreComputeSpectrogram({
    required String path,
    required double windowS,
    required double timeStepS,
    required double maxFreqHz,
    required double preEmphasisHz,
  });

  String crateApiCoreCoreVersion();

  String crateApiCoreEcho({required String input});

  Future<F0TrackData> crateApiCoreF0Track({
    required String path,
    required double timeStepS,
    required double f0MinHz,
    required double f0MaxHz,
  });

  Future<FormantTrackData> crateApiCoreFormantTrack({
    required String path,
    required double timeStepS,
    required int maxFormants,
    required double ceilingHz,
  });

  String crateApiCoreFormatPitchEdits({required PitchEditsData data});

  Future<void> crateApiCoreInitApp();

  Future<IntensityTrackData> crateApiCoreIntensityTrack({
    required String path,
    required double timeStepS,
    required double minPitchHz,
  });

  PitchEditsData crateApiCoreParsePitchEdits({required String text});

  String crateApiCorePitchEditsPath({required String wavPath});

  Future<TextGridData> crateApiCoreReadTextGrid({required String path});

  Future<VoiceReportData> crateApiCoreVoiceReport({
    required String path,
    required double f0MinHz,
    required double f0MaxHz,
  });

  Future<WavInfo> crateApiCoreWavInfo({required String path});

  Future<QualityData> crateApiCoreWavQuality({required String path});

  Future<void> crateApiCoreWriteTextGrid({
    required String path,
    required TextGridData data,
  });

  RustArcIncrementStrongCountFnType get rust_arc_increment_strong_count_Sound;

  RustArcDecrementStrongCountFnType get rust_arc_decrement_strong_count_Sound;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_SoundPtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  int crateApiCoreSoundChannels({required Sound that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSound(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_16,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCoreSoundChannelsConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCoreSoundChannelsConstMeta =>
      const TaskConstMeta(debugName: "Sound_channels", argNames: ["that"]);

  @override
  double crateApiCoreSoundDurationS({required Sound that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSound(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_f_64,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCoreSoundDurationSConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCoreSoundDurationSConstMeta =>
      const TaskConstMeta(debugName: "Sound_duration_s", argNames: ["that"]);

  @override
  Future<WaveformEnvelope> crateApiCoreSoundEnvelope({
    required Sound that,
    required double t0S,
    required double t1S,
    required int nBuckets,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSound(
            that,
            serializer,
          );
          sse_encode_f_64(t0S, serializer);
          sse_encode_f_64(t1S, serializer);
          sse_encode_u_32(nBuckets, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_waveform_envelope,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCoreSoundEnvelopeConstMeta,
        argValues: [that, t0S, t1S, nBuckets],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCoreSoundEnvelopeConstMeta => const TaskConstMeta(
    debugName: "Sound_envelope",
    argNames: ["that", "t0S", "t1S", "nBuckets"],
  );

  @override
  Future<void> crateApiCoreSoundExportRangeWav({
    required Sound that,
    required double t0S,
    required double t1S,
    required String path,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSound(
            that,
            serializer,
          );
          sse_encode_f_64(t0S, serializer);
          sse_encode_f_64(t1S, serializer);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCoreSoundExportRangeWavConstMeta,
        argValues: [that, t0S, t1S, path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCoreSoundExportRangeWavConstMeta =>
      const TaskConstMeta(
        debugName: "Sound_export_range_wav",
        argNames: ["that", "t0S", "t1S", "path"],
      );

  @override
  Future<F0TrackData> crateApiCoreSoundF0({
    required Sound that,
    required double timeStepS,
    required double f0MinHz,
    required double f0MaxHz,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSound(
            that,
            serializer,
          );
          sse_encode_f_64(timeStepS, serializer);
          sse_encode_f_64(f0MinHz, serializer);
          sse_encode_f_64(f0MaxHz, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_f_0_track_data,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCoreSoundF0ConstMeta,
        argValues: [that, timeStepS, f0MinHz, f0MaxHz],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCoreSoundF0ConstMeta => const TaskConstMeta(
    debugName: "Sound_f0",
    argNames: ["that", "timeStepS", "f0MinHz", "f0MaxHz"],
  );

  @override
  Future<F0CandidatesData> crateApiCoreSoundF0Candidates({
    required Sound that,
    required double timeStepS,
    required double f0MinHz,
    required double f0MaxHz,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSound(
            that,
            serializer,
          );
          sse_encode_f_64(timeStepS, serializer);
          sse_encode_f_64(f0MinHz, serializer);
          sse_encode_f_64(f0MaxHz, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_f_0_candidates_data,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCoreSoundF0CandidatesConstMeta,
        argValues: [that, timeStepS, f0MinHz, f0MaxHz],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCoreSoundF0CandidatesConstMeta =>
      const TaskConstMeta(
        debugName: "Sound_f0_candidates",
        argNames: ["that", "timeStepS", "f0MinHz", "f0MaxHz"],
      );

  @override
  Future<FormantTrackData> crateApiCoreSoundFormants({
    required Sound that,
    required double timeStepS,
    required int maxFormants,
    required double ceilingHz,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSound(
            that,
            serializer,
          );
          sse_encode_f_64(timeStepS, serializer);
          sse_encode_u_32(maxFormants, serializer);
          sse_encode_f_64(ceilingHz, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_formant_track_data,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCoreSoundFormantsConstMeta,
        argValues: [that, timeStepS, maxFormants, ceilingHz],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCoreSoundFormantsConstMeta => const TaskConstMeta(
    debugName: "Sound_formants",
    argNames: ["that", "timeStepS", "maxFormants", "ceilingHz"],
  );

  @override
  Future<IntensityTrackData> crateApiCoreSoundIntensity({
    required Sound that,
    required double timeStepS,
    required double minPitchHz,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSound(
            that,
            serializer,
          );
          sse_encode_f_64(timeStepS, serializer);
          sse_encode_f_64(minPitchHz, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_intensity_track_data,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCoreSoundIntensityConstMeta,
        argValues: [that, timeStepS, minPitchHz],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCoreSoundIntensityConstMeta => const TaskConstMeta(
    debugName: "Sound_intensity",
    argNames: ["that", "timeStepS", "minPitchHz"],
  );

  @override
  Future<Sound> crateApiCoreSoundLoad({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSound,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCoreSoundLoadConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCoreSoundLoadConstMeta =>
      const TaskConstMeta(debugName: "Sound_load", argNames: ["path"]);

  @override
  int crateApiCoreSoundSampleRate({required Sound that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSound(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCoreSoundSampleRateConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCoreSoundSampleRateConstMeta =>
      const TaskConstMeta(debugName: "Sound_sample_rate", argNames: ["that"]);

  @override
  Future<SpectrogramData> crateApiCoreSoundSpectrogramRange({
    required Sound that,
    required double t0S,
    required double t1S,
    required double windowS,
    required double timeStepS,
    required double maxFreqHz,
    required double preEmphasisHz,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSound(
            that,
            serializer,
          );
          sse_encode_f_64(t0S, serializer);
          sse_encode_f_64(t1S, serializer);
          sse_encode_f_64(windowS, serializer);
          sse_encode_f_64(timeStepS, serializer);
          sse_encode_f_64(maxFreqHz, serializer);
          sse_encode_f_64(preEmphasisHz, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_spectrogram_data,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCoreSoundSpectrogramRangeConstMeta,
        argValues: [
          that,
          t0S,
          t1S,
          windowS,
          timeStepS,
          maxFreqHz,
          preEmphasisHz,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCoreSoundSpectrogramRangeConstMeta =>
      const TaskConstMeta(
        debugName: "Sound_spectrogram_range",
        argNames: [
          "that",
          "t0S",
          "t1S",
          "windowS",
          "timeStepS",
          "maxFreqHz",
          "preEmphasisHz",
        ],
      );

  @override
  Future<VoiceReportData> crateApiCoreSoundVoiceReport({
    required Sound that,
    required double t0S,
    required double t1S,
    required double f0MinHz,
    required double f0MaxHz,
    F0TrackData? f0,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSound(
            that,
            serializer,
          );
          sse_encode_f_64(t0S, serializer);
          sse_encode_f_64(t1S, serializer);
          sse_encode_f_64(f0MinHz, serializer);
          sse_encode_f_64(f0MaxHz, serializer);
          sse_encode_opt_box_autoadd_f_0_track_data(f0, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_voice_report_data,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCoreSoundVoiceReportConstMeta,
        argValues: [that, t0S, t1S, f0MinHz, f0MaxHz, f0],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCoreSoundVoiceReportConstMeta =>
      const TaskConstMeta(
        debugName: "Sound_voice_report",
        argNames: ["that", "t0S", "t1S", "f0MinHz", "f0MaxHz", "f0"],
      );

  @override
  Future<SpectrogramData> crateApiCoreComputeSpectrogram({
    required String path,
    required double windowS,
    required double timeStepS,
    required double maxFreqHz,
    required double preEmphasisHz,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          sse_encode_f_64(windowS, serializer);
          sse_encode_f_64(timeStepS, serializer);
          sse_encode_f_64(maxFreqHz, serializer);
          sse_encode_f_64(preEmphasisHz, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_spectrogram_data,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCoreComputeSpectrogramConstMeta,
        argValues: [path, windowS, timeStepS, maxFreqHz, preEmphasisHz],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCoreComputeSpectrogramConstMeta =>
      const TaskConstMeta(
        debugName: "compute_spectrogram",
        argNames: [
          "path",
          "windowS",
          "timeStepS",
          "maxFreqHz",
          "preEmphasisHz",
        ],
      );

  @override
  String crateApiCoreCoreVersion() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 14)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCoreCoreVersionConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCoreCoreVersionConstMeta =>
      const TaskConstMeta(debugName: "core_version", argNames: []);

  @override
  String crateApiCoreEcho({required String input}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(input, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 15)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCoreEchoConstMeta,
        argValues: [input],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCoreEchoConstMeta =>
      const TaskConstMeta(debugName: "echo", argNames: ["input"]);

  @override
  Future<F0TrackData> crateApiCoreF0Track({
    required String path,
    required double timeStepS,
    required double f0MinHz,
    required double f0MaxHz,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          sse_encode_f_64(timeStepS, serializer);
          sse_encode_f_64(f0MinHz, serializer);
          sse_encode_f_64(f0MaxHz, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_f_0_track_data,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCoreF0TrackConstMeta,
        argValues: [path, timeStepS, f0MinHz, f0MaxHz],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCoreF0TrackConstMeta => const TaskConstMeta(
    debugName: "f0_track",
    argNames: ["path", "timeStepS", "f0MinHz", "f0MaxHz"],
  );

  @override
  Future<FormantTrackData> crateApiCoreFormantTrack({
    required String path,
    required double timeStepS,
    required int maxFormants,
    required double ceilingHz,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          sse_encode_f_64(timeStepS, serializer);
          sse_encode_u_32(maxFormants, serializer);
          sse_encode_f_64(ceilingHz, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_formant_track_data,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCoreFormantTrackConstMeta,
        argValues: [path, timeStepS, maxFormants, ceilingHz],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCoreFormantTrackConstMeta => const TaskConstMeta(
    debugName: "formant_track",
    argNames: ["path", "timeStepS", "maxFormants", "ceilingHz"],
  );

  @override
  String crateApiCoreFormatPitchEdits({required PitchEditsData data}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_pitch_edits_data(data, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 18)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCoreFormatPitchEditsConstMeta,
        argValues: [data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCoreFormatPitchEditsConstMeta =>
      const TaskConstMeta(debugName: "format_pitch_edits", argNames: ["data"]);

  @override
  Future<void> crateApiCoreInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCoreInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCoreInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<IntensityTrackData> crateApiCoreIntensityTrack({
    required String path,
    required double timeStepS,
    required double minPitchHz,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          sse_encode_f_64(timeStepS, serializer);
          sse_encode_f_64(minPitchHz, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_intensity_track_data,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCoreIntensityTrackConstMeta,
        argValues: [path, timeStepS, minPitchHz],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCoreIntensityTrackConstMeta => const TaskConstMeta(
    debugName: "intensity_track",
    argNames: ["path", "timeStepS", "minPitchHz"],
  );

  @override
  PitchEditsData crateApiCoreParsePitchEdits({required String text}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(text, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 21)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_pitch_edits_data,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCoreParsePitchEditsConstMeta,
        argValues: [text],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCoreParsePitchEditsConstMeta =>
      const TaskConstMeta(debugName: "parse_pitch_edits", argNames: ["text"]);

  @override
  String crateApiCorePitchEditsPath({required String wavPath}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(wavPath, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 22)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCorePitchEditsPathConstMeta,
        argValues: [wavPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCorePitchEditsPathConstMeta =>
      const TaskConstMeta(debugName: "pitch_edits_path", argNames: ["wavPath"]);

  @override
  Future<TextGridData> crateApiCoreReadTextGrid({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 23,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_text_grid_data,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCoreReadTextGridConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCoreReadTextGridConstMeta =>
      const TaskConstMeta(debugName: "read_text_grid", argNames: ["path"]);

  @override
  Future<VoiceReportData> crateApiCoreVoiceReport({
    required String path,
    required double f0MinHz,
    required double f0MaxHz,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          sse_encode_f_64(f0MinHz, serializer);
          sse_encode_f_64(f0MaxHz, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 24,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_voice_report_data,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCoreVoiceReportConstMeta,
        argValues: [path, f0MinHz, f0MaxHz],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCoreVoiceReportConstMeta => const TaskConstMeta(
    debugName: "voice_report",
    argNames: ["path", "f0MinHz", "f0MaxHz"],
  );

  @override
  Future<WavInfo> crateApiCoreWavInfo({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 25,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_wav_info,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCoreWavInfoConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCoreWavInfoConstMeta =>
      const TaskConstMeta(debugName: "wav_info", argNames: ["path"]);

  @override
  Future<QualityData> crateApiCoreWavQuality({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 26,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_quality_data,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCoreWavQualityConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCoreWavQualityConstMeta =>
      const TaskConstMeta(debugName: "wav_quality", argNames: ["path"]);

  @override
  Future<void> crateApiCoreWriteTextGrid({
    required String path,
    required TextGridData data,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          sse_encode_box_autoadd_text_grid_data(data, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 27,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCoreWriteTextGridConstMeta,
        argValues: [path, data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCoreWriteTextGridConstMeta => const TaskConstMeta(
    debugName: "write_text_grid",
    argNames: ["path", "data"],
  );

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_Sound => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSound;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_Sound => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSound;

  @protected
  Sound
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSound(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SoundImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Sound
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSound(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SoundImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Sound
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSound(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SoundImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  F0TrackData dco_decode_box_autoadd_f_0_track_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_f_0_track_data(raw);
  }

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  PitchEditsData dco_decode_box_autoadd_pitch_edits_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_pitch_edits_data(raw);
  }

  @protected
  TextGridData dco_decode_box_autoadd_text_grid_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_text_grid_data(raw);
  }

  @protected
  F0CandidatesData dco_decode_f_0_candidates_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return F0CandidatesData(
      timesS: dco_decode_list_prim_f_64_strict(arr[0]),
      f0Hz: dco_decode_list_prim_f_64_strict(arr[1]),
      candidatesHz: dco_decode_list_prim_f_64_strict(arr[2]),
      maxCandidates: dco_decode_u_32(arr[3]),
    );
  }

  @protected
  F0TrackData dco_decode_f_0_track_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return F0TrackData(
      timesS: dco_decode_list_prim_f_64_strict(arr[0]),
      f0Hz: dco_decode_list_prim_f_64_strict(arr[1]),
    );
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  FormantTrackData dco_decode_formant_track_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return FormantTrackData(
      timesS: dco_decode_list_prim_f_64_strict(arr[0]),
      maxFormants: dco_decode_u_32(arr[1]),
      formantsHz: dco_decode_list_prim_f_64_strict(arr[2]),
      bandwidthsHz: dco_decode_list_prim_f_64_strict(arr[3]),
    );
  }

  @protected
  IntensityTrackData dco_decode_intensity_track_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return IntensityTrackData(
      timesS: dco_decode_list_prim_f_64_strict(arr[0]),
      db: dco_decode_list_prim_f_64_strict(arr[1]),
    );
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  Float32List dco_decode_list_prim_f_32_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Float32List;
  }

  @protected
  Float64List dco_decode_list_prim_f_64_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Float64List;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<TextGridTierData> dco_decode_list_text_grid_tier_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_text_grid_tier_data).toList();
  }

  @protected
  F0TrackData? dco_decode_opt_box_autoadd_f_0_track_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_f_0_track_data(raw);
  }

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_f_64(raw);
  }

  @protected
  PitchEditsData dco_decode_pitch_edits_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return PitchEditsData(
      timeStepS: dco_decode_f_64(arr[0]),
      f0MinHz: dco_decode_f_64(arr[1]),
      f0MaxHz: dco_decode_f_64(arr[2]),
      timesS: dco_decode_list_prim_f_64_strict(arr[3]),
      f0Hz: dco_decode_list_prim_f_64_strict(arr[4]),
    );
  }

  @protected
  QualityData dco_decode_quality_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return QualityData(
      peakDbfs: dco_decode_f_64(arr[0]),
      clippedPct: dco_decode_f_64(arr[1]),
      estSnrDb: dco_decode_opt_box_autoadd_f_64(arr[2]),
    );
  }

  @protected
  SpectrogramData dco_decode_spectrogram_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return SpectrogramData(
      nFrames: dco_decode_u_32(arr[0]),
      nBins: dco_decode_u_32(arr[1]),
      firstTimeS: dco_decode_f_64(arr[2]),
      timeStepS: dco_decode_f_64(arr[3]),
      freqStepHz: dco_decode_f_64(arr[4]),
      valuesDb: dco_decode_list_prim_f_32_strict(arr[5]),
    );
  }

  @protected
  TextGridData dco_decode_text_grid_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return TextGridData(
      xmin: dco_decode_f_64(arr[0]),
      xmax: dco_decode_f_64(arr[1]),
      tiers: dco_decode_list_text_grid_tier_data(arr[2]),
    );
  }

  @protected
  TextGridTierData dco_decode_text_grid_tier_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return TextGridTierData(
      isPoint: dco_decode_bool(arr[0]),
      name: dco_decode_String(arr[1]),
      xmin: dco_decode_f_64(arr[2]),
      xmax: dco_decode_f_64(arr[3]),
      xmins: dco_decode_list_prim_f_64_strict(arr[4]),
      xmaxs: dco_decode_list_prim_f_64_strict(arr[5]),
      texts: dco_decode_list_String(arr[6]),
    );
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  VoiceReportData dco_decode_voice_report_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return VoiceReportData(
      meanHnrDb: dco_decode_opt_box_autoadd_f_64(arr[0]),
      nPeriods: dco_decode_u_64(arr[1]),
      jitterLocal: dco_decode_opt_box_autoadd_f_64(arr[2]),
      shimmerLocal: dco_decode_opt_box_autoadd_f_64(arr[3]),
      medianF0Hz: dco_decode_opt_box_autoadd_f_64(arr[4]),
      meanF0Hz: dco_decode_opt_box_autoadd_f_64(arr[5]),
      sdF0Hz: dco_decode_opt_box_autoadd_f_64(arr[6]),
    );
  }

  @protected
  WavInfo dco_decode_wav_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return WavInfo(
      sampleRate: dco_decode_u_32(arr[0]),
      channels: dco_decode_u_16(arr[1]),
      nSamples: dco_decode_u_64(arr[2]),
      durationS: dco_decode_f_64(arr[3]),
    );
  }

  @protected
  WaveformEnvelope dco_decode_waveform_envelope(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return WaveformEnvelope(
      min: dco_decode_list_prim_f_32_strict(arr[0]),
      max: dco_decode_list_prim_f_32_strict(arr[1]),
    );
  }

  @protected
  Sound
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSound(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return SoundImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  Sound
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSound(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return SoundImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  Sound
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSound(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return SoundImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  F0TrackData sse_decode_box_autoadd_f_0_track_data(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_f_0_track_data(deserializer));
  }

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_f_64(deserializer));
  }

  @protected
  PitchEditsData sse_decode_box_autoadd_pitch_edits_data(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_pitch_edits_data(deserializer));
  }

  @protected
  TextGridData sse_decode_box_autoadd_text_grid_data(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_text_grid_data(deserializer));
  }

  @protected
  F0CandidatesData sse_decode_f_0_candidates_data(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_timesS = sse_decode_list_prim_f_64_strict(deserializer);
    var var_f0Hz = sse_decode_list_prim_f_64_strict(deserializer);
    var var_candidatesHz = sse_decode_list_prim_f_64_strict(deserializer);
    var var_maxCandidates = sse_decode_u_32(deserializer);
    return F0CandidatesData(
      timesS: var_timesS,
      f0Hz: var_f0Hz,
      candidatesHz: var_candidatesHz,
      maxCandidates: var_maxCandidates,
    );
  }

  @protected
  F0TrackData sse_decode_f_0_track_data(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_timesS = sse_decode_list_prim_f_64_strict(deserializer);
    var var_f0Hz = sse_decode_list_prim_f_64_strict(deserializer);
    return F0TrackData(timesS: var_timesS, f0Hz: var_f0Hz);
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  FormantTrackData sse_decode_formant_track_data(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_timesS = sse_decode_list_prim_f_64_strict(deserializer);
    var var_maxFormants = sse_decode_u_32(deserializer);
    var var_formantsHz = sse_decode_list_prim_f_64_strict(deserializer);
    var var_bandwidthsHz = sse_decode_list_prim_f_64_strict(deserializer);
    return FormantTrackData(
      timesS: var_timesS,
      maxFormants: var_maxFormants,
      formantsHz: var_formantsHz,
      bandwidthsHz: var_bandwidthsHz,
    );
  }

  @protected
  IntensityTrackData sse_decode_intensity_track_data(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_timesS = sse_decode_list_prim_f_64_strict(deserializer);
    var var_db = sse_decode_list_prim_f_64_strict(deserializer);
    return IntensityTrackData(timesS: var_timesS, db: var_db);
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  Float32List sse_decode_list_prim_f_32_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getFloat32List(len_);
  }

  @protected
  Float64List sse_decode_list_prim_f_64_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getFloat64List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<TextGridTierData> sse_decode_list_text_grid_tier_data(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <TextGridTierData>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_text_grid_tier_data(deserializer));
    }
    return ans_;
  }

  @protected
  F0TrackData? sse_decode_opt_box_autoadd_f_0_track_data(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_f_0_track_data(deserializer));
    } else {
      return null;
    }
  }

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_f_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PitchEditsData sse_decode_pitch_edits_data(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_timeStepS = sse_decode_f_64(deserializer);
    var var_f0MinHz = sse_decode_f_64(deserializer);
    var var_f0MaxHz = sse_decode_f_64(deserializer);
    var var_timesS = sse_decode_list_prim_f_64_strict(deserializer);
    var var_f0Hz = sse_decode_list_prim_f_64_strict(deserializer);
    return PitchEditsData(
      timeStepS: var_timeStepS,
      f0MinHz: var_f0MinHz,
      f0MaxHz: var_f0MaxHz,
      timesS: var_timesS,
      f0Hz: var_f0Hz,
    );
  }

  @protected
  QualityData sse_decode_quality_data(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_peakDbfs = sse_decode_f_64(deserializer);
    var var_clippedPct = sse_decode_f_64(deserializer);
    var var_estSnrDb = sse_decode_opt_box_autoadd_f_64(deserializer);
    return QualityData(
      peakDbfs: var_peakDbfs,
      clippedPct: var_clippedPct,
      estSnrDb: var_estSnrDb,
    );
  }

  @protected
  SpectrogramData sse_decode_spectrogram_data(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_nFrames = sse_decode_u_32(deserializer);
    var var_nBins = sse_decode_u_32(deserializer);
    var var_firstTimeS = sse_decode_f_64(deserializer);
    var var_timeStepS = sse_decode_f_64(deserializer);
    var var_freqStepHz = sse_decode_f_64(deserializer);
    var var_valuesDb = sse_decode_list_prim_f_32_strict(deserializer);
    return SpectrogramData(
      nFrames: var_nFrames,
      nBins: var_nBins,
      firstTimeS: var_firstTimeS,
      timeStepS: var_timeStepS,
      freqStepHz: var_freqStepHz,
      valuesDb: var_valuesDb,
    );
  }

  @protected
  TextGridData sse_decode_text_grid_data(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_xmin = sse_decode_f_64(deserializer);
    var var_xmax = sse_decode_f_64(deserializer);
    var var_tiers = sse_decode_list_text_grid_tier_data(deserializer);
    return TextGridData(xmin: var_xmin, xmax: var_xmax, tiers: var_tiers);
  }

  @protected
  TextGridTierData sse_decode_text_grid_tier_data(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_isPoint = sse_decode_bool(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_xmin = sse_decode_f_64(deserializer);
    var var_xmax = sse_decode_f_64(deserializer);
    var var_xmins = sse_decode_list_prim_f_64_strict(deserializer);
    var var_xmaxs = sse_decode_list_prim_f_64_strict(deserializer);
    var var_texts = sse_decode_list_String(deserializer);
    return TextGridTierData(
      isPoint: var_isPoint,
      name: var_name,
      xmin: var_xmin,
      xmax: var_xmax,
      xmins: var_xmins,
      xmaxs: var_xmaxs,
      texts: var_texts,
    );
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  VoiceReportData sse_decode_voice_report_data(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_meanHnrDb = sse_decode_opt_box_autoadd_f_64(deserializer);
    var var_nPeriods = sse_decode_u_64(deserializer);
    var var_jitterLocal = sse_decode_opt_box_autoadd_f_64(deserializer);
    var var_shimmerLocal = sse_decode_opt_box_autoadd_f_64(deserializer);
    var var_medianF0Hz = sse_decode_opt_box_autoadd_f_64(deserializer);
    var var_meanF0Hz = sse_decode_opt_box_autoadd_f_64(deserializer);
    var var_sdF0Hz = sse_decode_opt_box_autoadd_f_64(deserializer);
    return VoiceReportData(
      meanHnrDb: var_meanHnrDb,
      nPeriods: var_nPeriods,
      jitterLocal: var_jitterLocal,
      shimmerLocal: var_shimmerLocal,
      medianF0Hz: var_medianF0Hz,
      meanF0Hz: var_meanF0Hz,
      sdF0Hz: var_sdF0Hz,
    );
  }

  @protected
  WavInfo sse_decode_wav_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_sampleRate = sse_decode_u_32(deserializer);
    var var_channels = sse_decode_u_16(deserializer);
    var var_nSamples = sse_decode_u_64(deserializer);
    var var_durationS = sse_decode_f_64(deserializer);
    return WavInfo(
      sampleRate: var_sampleRate,
      channels: var_channels,
      nSamples: var_nSamples,
      durationS: var_durationS,
    );
  }

  @protected
  WaveformEnvelope sse_decode_waveform_envelope(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_min = sse_decode_list_prim_f_32_strict(deserializer);
    var var_max = sse_decode_list_prim_f_32_strict(deserializer);
    return WaveformEnvelope(min: var_min, max: var_max);
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSound(
    Sound self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as SoundImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSound(
    Sound self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as SoundImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSound(
    Sound self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as SoundImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_f_0_track_data(
    F0TrackData self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_0_track_data(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_pitch_edits_data(
    PitchEditsData self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_pitch_edits_data(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_text_grid_data(
    TextGridData self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_text_grid_data(self, serializer);
  }

  @protected
  void sse_encode_f_0_candidates_data(
    F0CandidatesData self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_f_64_strict(self.timesS, serializer);
    sse_encode_list_prim_f_64_strict(self.f0Hz, serializer);
    sse_encode_list_prim_f_64_strict(self.candidatesHz, serializer);
    sse_encode_u_32(self.maxCandidates, serializer);
  }

  @protected
  void sse_encode_f_0_track_data(F0TrackData self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_f_64_strict(self.timesS, serializer);
    sse_encode_list_prim_f_64_strict(self.f0Hz, serializer);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_formant_track_data(
    FormantTrackData self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_f_64_strict(self.timesS, serializer);
    sse_encode_u_32(self.maxFormants, serializer);
    sse_encode_list_prim_f_64_strict(self.formantsHz, serializer);
    sse_encode_list_prim_f_64_strict(self.bandwidthsHz, serializer);
  }

  @protected
  void sse_encode_intensity_track_data(
    IntensityTrackData self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_f_64_strict(self.timesS, serializer);
    sse_encode_list_prim_f_64_strict(self.db, serializer);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_f_32_strict(
    Float32List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putFloat32List(self);
  }

  @protected
  void sse_encode_list_prim_f_64_strict(
    Float64List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putFloat64List(self);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_text_grid_tier_data(
    List<TextGridTierData> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_text_grid_tier_data(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_f_0_track_data(
    F0TrackData? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_f_0_track_data(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_f_64(self, serializer);
    }
  }

  @protected
  void sse_encode_pitch_edits_data(
    PitchEditsData self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self.timeStepS, serializer);
    sse_encode_f_64(self.f0MinHz, serializer);
    sse_encode_f_64(self.f0MaxHz, serializer);
    sse_encode_list_prim_f_64_strict(self.timesS, serializer);
    sse_encode_list_prim_f_64_strict(self.f0Hz, serializer);
  }

  @protected
  void sse_encode_quality_data(QualityData self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self.peakDbfs, serializer);
    sse_encode_f_64(self.clippedPct, serializer);
    sse_encode_opt_box_autoadd_f_64(self.estSnrDb, serializer);
  }

  @protected
  void sse_encode_spectrogram_data(
    SpectrogramData self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.nFrames, serializer);
    sse_encode_u_32(self.nBins, serializer);
    sse_encode_f_64(self.firstTimeS, serializer);
    sse_encode_f_64(self.timeStepS, serializer);
    sse_encode_f_64(self.freqStepHz, serializer);
    sse_encode_list_prim_f_32_strict(self.valuesDb, serializer);
  }

  @protected
  void sse_encode_text_grid_data(TextGridData self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self.xmin, serializer);
    sse_encode_f_64(self.xmax, serializer);
    sse_encode_list_text_grid_tier_data(self.tiers, serializer);
  }

  @protected
  void sse_encode_text_grid_tier_data(
    TextGridTierData self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.isPoint, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_f_64(self.xmin, serializer);
    sse_encode_f_64(self.xmax, serializer);
    sse_encode_list_prim_f_64_strict(self.xmins, serializer);
    sse_encode_list_prim_f_64_strict(self.xmaxs, serializer);
    sse_encode_list_String(self.texts, serializer);
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_voice_report_data(
    VoiceReportData self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_box_autoadd_f_64(self.meanHnrDb, serializer);
    sse_encode_u_64(self.nPeriods, serializer);
    sse_encode_opt_box_autoadd_f_64(self.jitterLocal, serializer);
    sse_encode_opt_box_autoadd_f_64(self.shimmerLocal, serializer);
    sse_encode_opt_box_autoadd_f_64(self.medianF0Hz, serializer);
    sse_encode_opt_box_autoadd_f_64(self.meanF0Hz, serializer);
    sse_encode_opt_box_autoadd_f_64(self.sdF0Hz, serializer);
  }

  @protected
  void sse_encode_wav_info(WavInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.sampleRate, serializer);
    sse_encode_u_16(self.channels, serializer);
    sse_encode_u_64(self.nSamples, serializer);
    sse_encode_f_64(self.durationS, serializer);
  }

  @protected
  void sse_encode_waveform_envelope(
    WaveformEnvelope self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_f_32_strict(self.min, serializer);
    sse_encode_list_prim_f_32_strict(self.max, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}

@sealed
class SoundImpl extends RustOpaque implements Sound {
  // Not to be used by end users
  SoundImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  SoundImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_Sound,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_Sound,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_SoundPtr,
  );

  int channels() => RustLib.instance.api.crateApiCoreSoundChannels(that: this);

  double durationS() =>
      RustLib.instance.api.crateApiCoreSoundDurationS(that: this);

  Future<WaveformEnvelope> envelope({
    required double t0S,
    required double t1S,
    required int nBuckets,
  }) => RustLib.instance.api.crateApiCoreSoundEnvelope(
    that: this,
    t0S: t0S,
    t1S: t1S,
    nBuckets: nBuckets,
  );

  /// Write `[t0_s, t1_s]` (clamped) as a 16-bit mono WAV at `path` —
  /// Praat's "extract selection", for building stimuli and examples.
  Future<void> exportRangeWav({
    required double t0S,
    required double t1S,
    required String path,
  }) => RustLib.instance.api.crateApiCoreSoundExportRangeWav(
    that: this,
    t0S: t0S,
    t1S: t1S,
    path: path,
  );

  Future<F0TrackData> f0({
    required double timeStepS,
    required double f0MinHz,
    required double f0MaxHz,
  }) => RustLib.instance.api.crateApiCoreSoundF0(
    that: this,
    timeStepS: timeStepS,
    f0MinHz: f0MinHz,
    f0MaxHz: f0MaxHz,
  );

  Future<F0CandidatesData> f0Candidates({
    required double timeStepS,
    required double f0MinHz,
    required double f0MaxHz,
  }) => RustLib.instance.api.crateApiCoreSoundF0Candidates(
    that: this,
    timeStepS: timeStepS,
    f0MinHz: f0MinHz,
    f0MaxHz: f0MaxHz,
  );

  Future<FormantTrackData> formants({
    required double timeStepS,
    required int maxFormants,
    required double ceilingHz,
  }) => RustLib.instance.api.crateApiCoreSoundFormants(
    that: this,
    timeStepS: timeStepS,
    maxFormants: maxFormants,
    ceilingHz: ceilingHz,
  );

  Future<IntensityTrackData> intensity({
    required double timeStepS,
    required double minPitchHz,
  }) => RustLib.instance.api.crateApiCoreSoundIntensity(
    that: this,
    timeStepS: timeStepS,
    minPitchHz: minPitchHz,
  );

  int sampleRate() =>
      RustLib.instance.api.crateApiCoreSoundSampleRate(that: this);

  Future<SpectrogramData> spectrogramRange({
    required double t0S,
    required double t1S,
    required double windowS,
    required double timeStepS,
    required double maxFreqHz,
    required double preEmphasisHz,
  }) => RustLib.instance.api.crateApiCoreSoundSpectrogramRange(
    that: this,
    t0S: t0S,
    t1S: t1S,
    windowS: windowS,
    timeStepS: timeStepS,
    maxFreqHz: maxFreqHz,
    preEmphasisHz: preEmphasisHz,
  );

  /// Voice report over `[t0_s, t1_s]` (clamped to the file). An empty or
  /// inverted range yields an empty report rather than an error, so the
  /// UI can treat "nothing analyzable" uniformly with "too short".
  ///
  /// `f0`, when given, is the whole recording's displayed track, manual
  /// corrections included; its frames inside the range drive the glottal
  /// pulses and the F0 summary. Without it the range is tracked afresh.
  Future<VoiceReportData> voiceReport({
    required double t0S,
    required double t1S,
    required double f0MinHz,
    required double f0MaxHz,
    F0TrackData? f0,
  }) => RustLib.instance.api.crateApiCoreSoundVoiceReport(
    that: this,
    t0S: t0S,
    t1S: t1S,
    f0MinHz: f0MinHz,
    f0MaxHz: f0MaxHz,
    f0: f0,
  );
}
