// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `formant_to_data`, `spectrogram_to_data`, `voice_report_data`

String coreVersion() => RustLib.instance.api.crateApiCoreCoreVersion();

String echo({required String input}) =>
    RustLib.instance.api.crateApiCoreEcho(input: input);

Future<WavInfo> wavInfo({required String path}) =>
    RustLib.instance.api.crateApiCoreWavInfo(path: path);

Future<QualityData> wavQuality({required String path}) =>
    RustLib.instance.api.crateApiCoreWavQuality(path: path);

Future<VoiceReportData> voiceReport({
  required String path,
  required double f0MinHz,
  required double f0MaxHz,
}) => RustLib.instance.api.crateApiCoreVoiceReport(
  path: path,
  f0MinHz: f0MinHz,
  f0MaxHz: f0MaxHz,
);

Future<F0TrackData> f0Track({
  required String path,
  required double timeStepS,
  required double f0MinHz,
  required double f0MaxHz,
}) => RustLib.instance.api.crateApiCoreF0Track(
  path: path,
  timeStepS: timeStepS,
  f0MinHz: f0MinHz,
  f0MaxHz: f0MaxHz,
);

String pitchEditsPath({required String wavPath}) =>
    RustLib.instance.api.crateApiCorePitchEditsPath(wavPath: wavPath);

PitchEditsData parsePitchEdits({required String text}) =>
    RustLib.instance.api.crateApiCoreParsePitchEdits(text: text);

String formatPitchEdits({required PitchEditsData data}) =>
    RustLib.instance.api.crateApiCoreFormatPitchEdits(data: data);

Future<IntensityTrackData> intensityTrack({
  required String path,
  required double timeStepS,
  required double minPitchHz,
}) => RustLib.instance.api.crateApiCoreIntensityTrack(
  path: path,
  timeStepS: timeStepS,
  minPitchHz: minPitchHz,
);

Future<SpectrogramData> computeSpectrogram({
  required String path,
  required double windowS,
  required double timeStepS,
  required double maxFreqHz,
  required double preEmphasisHz,
}) => RustLib.instance.api.crateApiCoreComputeSpectrogram(
  path: path,
  windowS: windowS,
  timeStepS: timeStepS,
  maxFreqHz: maxFreqHz,
  preEmphasisHz: preEmphasisHz,
);

Future<FormantTrackData> formantTrack({
  required String path,
  required double timeStepS,
  required int maxFormants,
  required double ceilingHz,
}) => RustLib.instance.api.crateApiCoreFormantTrack(
  path: path,
  timeStepS: timeStepS,
  maxFormants: maxFormants,
  ceilingHz: ceilingHz,
);

Future<TextGridData> readTextGrid({required String path}) =>
    RustLib.instance.api.crateApiCoreReadTextGrid(path: path);

Future<void> writeTextGrid({
  required String path,
  required TextGridData data,
}) => RustLib.instance.api.crateApiCoreWriteTextGrid(path: path, data: data);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Sound>>
abstract class Sound implements RustOpaqueInterface {
  int channels();

  double durationS();

  Future<WaveformEnvelope> envelope({
    required double t0S,
    required double t1S,
    required int nBuckets,
  });

  /// Write `[t0_s, t1_s]` (clamped) as a 16-bit mono WAV at `path` —
  /// Praat's "extract selection", for building stimuli and examples.
  Future<void> exportRangeWav({
    required double t0S,
    required double t1S,
    required String path,
  });

  Future<F0TrackData> f0({
    required double timeStepS,
    required double f0MinHz,
    required double f0MaxHz,
  });

  Future<F0CandidatesData> f0Candidates({
    required double timeStepS,
    required double f0MinHz,
    required double f0MaxHz,
  });

  Future<FormantTrackData> formants({
    required double timeStepS,
    required int maxFormants,
    required double ceilingHz,
  });

  Future<IntensityTrackData> intensity({
    required double timeStepS,
    required double minPitchHz,
  });

  static Future<Sound> load({required String path}) =>
      RustLib.instance.api.crateApiCoreSoundLoad(path: path);

  int sampleRate();

  Future<SpectrogramData> spectrogramRange({
    required double t0S,
    required double t1S,
    required double windowS,
    required double timeStepS,
    required double maxFreqHz,
    required double preEmphasisHz,
  });

  /// Voice report over `[t0_s, t1_s]` (clamped to the file). An empty or
  /// inverted range yields an empty report rather than an error, so the
  /// UI can treat "nothing analyzable" uniformly with "too short".
  ///
  /// `f0`, when given, is the whole recording's displayed track, manual
  /// corrections included; its frames inside the range drive the glottal
  /// pulses and the F0 summary. Without it the range is tracked afresh.
  Future<VoiceReportData> voiceReport({
    required double t0S,
    required double t1S,
    required double f0MinHz,
    required double f0MaxHz,
    F0TrackData? f0,
  });
}

/// F0 path plus each frame's voiced candidates, for manual correction.
class F0CandidatesData {
  final Float64List timesS;

  /// Selected path; 0.0 marks an unvoiced frame.
  final Float64List f0Hz;

  /// Row-major, `max_candidates` per frame, cheapest first; 0.0 pads.
  final Float64List candidatesHz;
  final int maxCandidates;

  const F0CandidatesData({
    required this.timesS,
    required this.f0Hz,
    required this.candidatesHz,
    required this.maxCandidates,
  });

  @override
  int get hashCode =>
      timesS.hashCode ^
      f0Hz.hashCode ^
      candidatesHz.hashCode ^
      maxCandidates.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is F0CandidatesData &&
          runtimeType == other.runtimeType &&
          timesS == other.timesS &&
          f0Hz == other.f0Hz &&
          candidatesHz == other.candidatesHz &&
          maxCandidates == other.maxCandidates;
}

class F0TrackData {
  final Float64List timesS;

  /// F0 in Hz; 0.0 marks an unvoiced frame.
  final Float64List f0Hz;

  const F0TrackData({required this.timesS, required this.f0Hz});

  @override
  int get hashCode => timesS.hashCode ^ f0Hz.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is F0TrackData &&
          runtimeType == other.runtimeType &&
          timesS == other.timesS &&
          f0Hz == other.f0Hz;
}

class FormantTrackData {
  final Float64List timesS;
  final int maxFormants;

  /// Frame-major matrix `[frame * max_formants + i]`; 0.0 = no formant.
  final Float64List formantsHz;

  /// Same layout as `formants_hz`.
  final Float64List bandwidthsHz;

  const FormantTrackData({
    required this.timesS,
    required this.maxFormants,
    required this.formantsHz,
    required this.bandwidthsHz,
  });

  @override
  int get hashCode =>
      timesS.hashCode ^
      maxFormants.hashCode ^
      formantsHz.hashCode ^
      bandwidthsHz.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FormantTrackData &&
          runtimeType == other.runtimeType &&
          timesS == other.timesS &&
          maxFormants == other.maxFormants &&
          formantsHz == other.formantsHz &&
          bandwidthsHz == other.bandwidthsHz;
}

class IntensityTrackData {
  final Float64List timesS;
  final Float64List db;

  const IntensityTrackData({required this.timesS, required this.db});

  @override
  int get hashCode => timesS.hashCode ^ db.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IntensityTrackData &&
          runtimeType == other.runtimeType &&
          timesS == other.timesS &&
          db == other.db;
}

/// Manual F0 corrections as stored in `<stem>.pitchedits.csv`.
class PitchEditsData {
  final double timeStepS;
  final double f0MinHz;
  final double f0MaxHz;
  final Float64List timesS;

  /// 0.0 marks a frame set to unvoiced.
  final Float64List f0Hz;

  const PitchEditsData({
    required this.timeStepS,
    required this.f0MinHz,
    required this.f0MaxHz,
    required this.timesS,
    required this.f0Hz,
  });

  @override
  int get hashCode =>
      timeStepS.hashCode ^
      f0MinHz.hashCode ^
      f0MaxHz.hashCode ^
      timesS.hashCode ^
      f0Hz.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PitchEditsData &&
          runtimeType == other.runtimeType &&
          timeStepS == other.timeStepS &&
          f0MinHz == other.f0MinHz &&
          f0MaxHz == other.f0MaxHz &&
          timesS == other.timesS &&
          f0Hz == other.f0Hz;
}

class QualityData {
  /// Highest sample magnitude, dB re full scale (<= 0; -120 = silence).
  final double peakDbfs;

  /// Percentage of samples at or above one step below full scale.
  final double clippedPct;

  /// Percentile-based SNR estimate in dB; None for silent/too-short files.
  final double? estSnrDb;

  const QualityData({
    required this.peakDbfs,
    required this.clippedPct,
    this.estSnrDb,
  });

  @override
  int get hashCode =>
      peakDbfs.hashCode ^ clippedPct.hashCode ^ estSnrDb.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is QualityData &&
          runtimeType == other.runtimeType &&
          peakDbfs == other.peakDbfs &&
          clippedPct == other.clippedPct &&
          estSnrDb == other.estSnrDb;
}

class SpectrogramData {
  final int nFrames;
  final int nBins;
  final double firstTimeS;
  final double timeStepS;
  final double freqStepHz;

  /// Power in dB, frame-major: `values_db[frame * n_bins + bin]`.
  final Float32List valuesDb;

  const SpectrogramData({
    required this.nFrames,
    required this.nBins,
    required this.firstTimeS,
    required this.timeStepS,
    required this.freqStepHz,
    required this.valuesDb,
  });

  @override
  int get hashCode =>
      nFrames.hashCode ^
      nBins.hashCode ^
      firstTimeS.hashCode ^
      timeStepS.hashCode ^
      freqStepHz.hashCode ^
      valuesDb.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SpectrogramData &&
          runtimeType == other.runtimeType &&
          nFrames == other.nFrames &&
          nBins == other.nBins &&
          firstTimeS == other.firstTimeS &&
          timeStepS == other.timeStepS &&
          freqStepHz == other.freqStepHz &&
          valuesDb == other.valuesDb;
}

class TextGridData {
  final double xmin;
  final double xmax;
  final List<TextGridTierData> tiers;

  const TextGridData({
    required this.xmin,
    required this.xmax,
    required this.tiers,
  });

  @override
  int get hashCode => xmin.hashCode ^ xmax.hashCode ^ tiers.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TextGridData &&
          runtimeType == other.runtimeType &&
          xmin == other.xmin &&
          xmax == other.xmax &&
          tiers == other.tiers;
}

/// One annotation tier, flattened for the bridge. For interval tiers,
/// `xmins`/`xmaxs`/`texts` run in parallel; for point tiers `xmins` holds
/// the point times and `xmaxs` is empty.
class TextGridTierData {
  final bool isPoint;
  final String name;
  final double xmin;
  final double xmax;
  final Float64List xmins;
  final Float64List xmaxs;
  final List<String> texts;

  const TextGridTierData({
    required this.isPoint,
    required this.name,
    required this.xmin,
    required this.xmax,
    required this.xmins,
    required this.xmaxs,
    required this.texts,
  });

  @override
  int get hashCode =>
      isPoint.hashCode ^
      name.hashCode ^
      xmin.hashCode ^
      xmax.hashCode ^
      xmins.hashCode ^
      xmaxs.hashCode ^
      texts.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TextGridTierData &&
          runtimeType == other.runtimeType &&
          isPoint == other.isPoint &&
          name == other.name &&
          xmin == other.xmin &&
          xmax == other.xmax &&
          xmins == other.xmins &&
          xmaxs == other.xmaxs &&
          texts == other.texts;
}

class VoiceReportData {
  /// Mean harmonics-to-noise ratio over voiced frames, dB; None if none.
  final double? meanHnrDb;
  final BigInt nPeriods;

  /// Jitter (local); None with too few period pairs.
  final double? jitterLocal;

  /// Shimmer (local); None with too few pulses.
  final double? shimmerLocal;

  /// Median / mean / SD of F0 over voiced frames, Hz.
  final double? medianF0Hz;
  final double? meanF0Hz;
  final double? sdF0Hz;

  const VoiceReportData({
    this.meanHnrDb,
    required this.nPeriods,
    this.jitterLocal,
    this.shimmerLocal,
    this.medianF0Hz,
    this.meanF0Hz,
    this.sdF0Hz,
  });

  @override
  int get hashCode =>
      meanHnrDb.hashCode ^
      nPeriods.hashCode ^
      jitterLocal.hashCode ^
      shimmerLocal.hashCode ^
      medianF0Hz.hashCode ^
      meanF0Hz.hashCode ^
      sdF0Hz.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VoiceReportData &&
          runtimeType == other.runtimeType &&
          meanHnrDb == other.meanHnrDb &&
          nPeriods == other.nPeriods &&
          jitterLocal == other.jitterLocal &&
          shimmerLocal == other.shimmerLocal &&
          medianF0Hz == other.medianF0Hz &&
          meanF0Hz == other.meanF0Hz &&
          sdF0Hz == other.sdF0Hz;
}

class WavInfo {
  final int sampleRate;
  final int channels;
  final BigInt nSamples;
  final double durationS;

  const WavInfo({
    required this.sampleRate,
    required this.channels,
    required this.nSamples,
    required this.durationS,
  });

  @override
  int get hashCode =>
      sampleRate.hashCode ^
      channels.hashCode ^
      nSamples.hashCode ^
      durationS.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WavInfo &&
          runtimeType == other.runtimeType &&
          sampleRate == other.sampleRate &&
          channels == other.channels &&
          nSamples == other.nSamples &&
          durationS == other.durationS;
}

class WaveformEnvelope {
  /// Per-bucket minima; same length as `max`.
  final Float32List min;
  final Float32List max;

  const WaveformEnvelope({required this.min, required this.max});

  @override
  int get hashCode => min.hashCode ^ max.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WaveformEnvelope &&
          runtimeType == other.runtimeType &&
          min == other.min &&
          max == other.max;
}
